apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: spot
spec:
  role: kcp-cluster-auto-mode-node-role
  subnetSelectorTerms:
    - tags:
        Name: kcp-cluster-private-subnet-1
    - tags:
        Name: kcp-cluster-private-subnet-2
  securityGroupSelectorTerms:
    - tags:
        Name: kcp-cluster/ClusterSharedNodeSecurityGroup
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot
spec:
  limits:
    cpu: "4"
    memory: "8Gi"
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: spot
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["t", "c", "m", "r"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["2", "4", "8", "16", "32"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["eu-central-1a", "eu-central-1b"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64", "amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
    budgets:
      - nodes: 50%

