kcp:
  targetRevision: "0.12.0"
  certificateIssuer:
    name: letsencrypt
    kind: ClusterIssuer
  kcp:
    v: 9
  kcpFrontProxy:
    v: 9
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: true
  etcd:
    memory: "256Mi"
  volumeClassName: "standard"
  audit:
    enabled: false

controllers:
  - name: kcp-users-controller
    repoURL: "ghcr.io/cogniteo/helm-charts"
    chart: kcp-users-controller
    targetRevision: "0.*"
    destinationNamespace: "kcp"
    serviceAccountName: "users-controller"
    managedPolicies:
      - "arn:aws:iam::aws:policy/AmazonCognitoPowerUser"
    envs:
      LOG_LEVEL: debug
      COGNITO_USER_POOL_ID: "{{ $.Values.cognitoUserPoolId }}"
      VIRTUAL_WORKSPACE_URL: "https://{{ $.Values.externalHostname }}:443/services/apiexport/root/users"
