apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
  namespace: argocd
spec:
  project: default
  source:
    # The official cert-manager Helm repository
    repoURL: "https://charts.jetstack.io"
    # The name of the cert-manager chart
    chart: cert-manager
    # Specify the chart version; update this to the desired version
    targetRevision: "v1.11.0"
    helm:
      # Place any custom Helm values here
      values: |
        installCRDs: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true