apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: public.ecr.aws/aws-controllers-k8s
    targetRevision: "46.25.10"
    chart: ack-chart
    helm:
      releaseName: ack
      valuesObject:
        installCRDs: true
        cognitoidentityprovider:
          enabled: true
          aws:
            region: eu-central-1
        acm:
          enabled: true
          aws:
            region: eu-central-1
  destination:
    server: https://kubernetes.default.svc
    namespace: ack-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
