apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kcp-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: ingress-nginx
            path: manifests/core/applications/ingress-nginx.yaml
          - name: external-dns
            path: manifests/core/applications/external-dns.yaml
          - name: cert-manager
            path: manifests/core/applications/cert-manager.yaml
          - name: ack
            path: manifests/core/applications/ack.yaml
          - name: kcp
            path: manifests/core/applications/kcp.yaml
          - name: prometheus-stack
            path: manifests/core/applications/prometheus-stack.yaml
          - name: kcp-users-controller
            path: manifests/core/applications/kcp-users-controller.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/piotrjanik/kcp-poc
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
