# Helm values for Argo CD installation (mirrors Makefile --set flags)
configs:
  params:
    server.insecure: true
server:
  ingress:
    enabled: true
    hosts:
      - argocd.${DOMAIN}
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.${DOMAIN}
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
dex:
  enabled: false
notifications:
  enabled: false
