apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kcp-dev.github.io/helm-charts
    chart: kcp
    targetRevision: 0.10.1
    helm:
      releaseName: kcp
      valuesObject:
        externalHostname: "api.${DOMAIN}"
        kcpFrontProxy:
          v: 9
          service:
            type: ClusterIP
          certificateIssuer:
            name: letsencrypt
            kind: ClusterIssuer
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        etcd:
          resources:
            requests:
              memory: 256Mi
        kcp:
          v: 9
          volumeClassName: "standard"
        audit:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kcp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
