apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcp-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kcp-dev.github.io/helm-charts
    chart: kcp
    targetRevision: 0.10.0
    helm:
      releaseName: kcp
      valuesObject:
        externalHostname: "kcp.local.gd"
        kcpFrontProxy:
          v: 9
          ingress:
            enabled: true
          service:
            type: NodePort
            nodePort: 30443
            clusterIP: "10.96.0.100"
          certificateIssuer:
            name: selfsigned-cluster-issuer
            kind: ClusterIssuer
        externalPort: "30443"
        etcd:
          resources:
            requests:
              memory: 256Mi
        certificates:
          dnsNames:
            - localhost
            - kcp.local.gd
        kcp:
          # tag is set via --set flag to make it more dynamic for testing purposes
          v: 9
          volumeClassName: "standard"
          hostAliases:
            enabled: true
            values:
              - ip: "10.96.0.100"
                hostnames:
                  - "kcp.local.gd"
        audit:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kcp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true