apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kcp-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: middleware
            path: manifests/platform/middleware
          - name: kcp
            path: manifests/platform/kcp
            valuesObject:
              externalHostname: ${HOSTNAME}
          - name: cognito
            path: manifests/core/cognito
          - name: certificates
            path: manifests/platform/certificates
            valuesObject:
              letsencrypt:
                email: ${ACME_EMAIL}
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/piotrjanik/kcp-poc
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          valuesObject: {{ .valuesObject | toYaml }}
      destination:
        server: https://kubernetes.default.svc
        namespace: "argocd"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
