apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kcp-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: middleware
            path: manifests/platform/middleware
            helm: false
          - name: kcp-suite
            path: manifests/platform/kcp
            helm: true
            valuesObject:
              externalHostname: ${KCP_HOSTNAME}
          - name: cognito
            path: manifests/core/cognito
            helm: false
          - name: certificates
            path: manifests/platform/certificates
            helm: true
            valuesObject:
              letsencrypt:
                email: ${ACME_EMAIL}
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/piotrjanik/kcp-poc
        targetRevision: HEAD
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "argocd"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if .helm }}
    spec:
      source:
        helm:
          valuesObject:
            {{ .valuesObject | toYaml | nindent 20 }}
    {{- end }}
