apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/cloudnative-pg/charts"
    chart: cnpg
    targetRevision: "main"  # or specify a version tag/commit hash if needed
    helm:
      # Optionally, provide any values overrides in YAML format:
      values: |
        replicaCount: 1
        # Add other custom values as needed for your deployment.
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true