apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kcp-dev.github.io/helm-charts
    chart: api-syncagent
    targetRevision: 0.1.0
    helm:
      releaseName: sync-agent
      valuesObject:
        apiExportName: provider1
        kcpKubeconfig: platform-kubeconfig
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kcp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true