{{- /* Loop over each controller in values.controllers */ -}}
{{- range .Values.controllers }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .repoURL | quote }}
    chart: {{ .chart | quote }}
    targetRevision: {{ .targetRevision | quote }}
    helm: 
      valuesObject:
        controllerManager:
          serviceAccountName: {{ .serviceAccountName | quote }}
          container:
            image:
              tag: {{ .targetRevision | quote }}
            args:
              - "--client-cert=/etc/secrets/client-cert/tls.crt"
              - "--client-key=/etc/secrets/client-cert/tls.key"
              - "--ca-cert=/etc/secrets/client-cert/ca.crt"
            {{- if .envs }}
            env: 
              {{- include "common.tplvalues.render" (dict "value" .envs "context" $) | nindent 14 }}
            {{- end }}
          extraSecrets:
            - name: client-cert
              secretName: {{ .name }}-client-cert
              mountPath: /etc/secrets/client-cert
              readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .destinationNamespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}-client-cert
  namespace: {{ .destinationNamespace | quote }} 
spec:
  commonName: {{ .name }}
  issuerRef:
    name: kcp-front-proxy-client-issuer
  privateKey:
    algorithm: RSA
    size: 2048
  secretName: {{ .name }}-client-cert
  subject:
    organizations:
      - system:kcp:admin
  usages:
    - client auth
{{- if .managedPolicies }}
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: {{ .name }}
  namespace: {{ .destinationNamespace | quote }}
  annotations:
    services.k8s.aws/adoption-policy: "adopt-by-id"
    services.k8s.aws/adoption-fields: "name,metadata.name"
spec:
  name: {{ .name }}
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "pods.eks.amazonaws.com"
          },
          "Action": [
            "sts:AssumeRole",
            "sts:TagSession"
          ]
        }
      ]
    }
  description: "IAM Role for the {{ .name }} controller"
  policies:
    {{- range .managedPolicies }}
    - {{ . }}
    {{- end }}
  tags:
    - key: Name
      value: "{{ .name }}"
    - key: Controller
      value: {{ .name | quote }}
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  name: {{ .name }}
  namespace: {{ .destinationNamespace | quote }}
spec:
  namespace: {{ .destinationNamespace | quote }}
  clusterName: {{ $.Values.clusterName | quote }}
  serviceAccount: {{ .serviceAccountName | default (printf "%s-controller" .name) | quote }}
  roleRef:
    from:
      name: {{ .name }}
{{- end }}
{{- end }}