{{- /* KCP Application */ -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kcp-dev.github.io/helm-charts
    chart: kcp
    targetRevision: {{ .Values.kcp.targetRevision | quote }}
    helm:
      releaseName: kcp
      valuesObject:
        {{- include "common.tplvalues.render" (dict "value" .Values.kcp "context" $) | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kcp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
