apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kcp-dev.github.io/helm-charts
    chart: kcp
    targetRevision: 0.10.0
    helm:
      releaseName: kcp
      valuesObject:
        externalHostname: "api.kcp.piotrjanik.dev"
        kcpFrontProxy:
          v: 9
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
              external-dns.alpha.kubernetes.io/hostname: "api.kcp.piotrjanik.dev"
        etcd:
          resources:
            requests:
              memory: 256Mi
        # certificates:
        #   dnsNames:
        #     - api.kcp.piotrjanik.dev
        kcp:
          # tag is set via --set flag to make it more dynamic for testing purposes
          v: 9
          volumeClassName: "standard"
          hostAliases:
            enabled: true
            values:
              - ip: "10.96.0.100"
                hostnames:
                  - "api.kcp.piotrjanik.dev"
        audit:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kcp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true